### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by Fernando-Rodrigo** [DGKSK8LIFE/Weatherbot#2]
In the last line is an extra parenthesis closing the command and causing a error message.

**Comment by DGKSK8LIFE** [comment]
Thank you very much!

**Comment by DGKSK8LIFE** [comment]
Just fixed. I think that the actual source code I deployed (in a private repo) had the correct source, but when I went in the public repo to change the arg to the last method call, I must've added that extra paren. Lol weatherbot is a really old piece of shit that I wrote a while back; honestly a good feature to add would be reading credentials from a YAML/JSON file, instead of hardcoding them. That could be a feature to add in a PR...
